.TH caja\-actions\-print 1 "Feb 2015" "Version 1.8.0" "caja-actions"
.SH NAME
caja\-actions\-print \- print a menu or an action to stdout
.SH SYNOPSIS
\fBcaja\-actions\-print\fR [\fIOPTION\fR]
.SH DESCRIPTION
\fBcaja\-actions\-print\fR print a caja\-actions menu or action to stdout.
This program is intended to be used on the command\-line for scripting caja actions.
.SH OPTIONS
\fIHelp options\fR
.TP
\fB\-?, \-h, \-\-help\fR Show help options
.TP 
\fB\-\-help\-all\fR Show all help options
.TP 
\fB\-\-help\-misc\fR Show miscellaneous options
.TP
\fIMiscellaneous options\fR
.TP 
\fB-v, \-\-version\fR Output the version number
.TP
\fIApplication options\fR
.TP 
\fB\-i, \-\-id=STRING\fR The internal identifier of the action to be launched.
.TP 
\fB\-f, \-\-format=<STRING>\fR An export format [Desktop1]

.SH AUTHOR
\fIcaja\-actions\fR has been derived from \fInautilus\-actions\fR which has
been written by Rodrigo Moya <rodrigo[AT]novell.com>, Frederic Ruaudel
<grumz[AT]grumz.net>, Pierre Wieser <pwieser[AT]trychlos.org>, and
contributors.
.PP
The porting work to the MATE desktop environment under the extension name
\fIcaja\-actions\fR has been done by Wolfgang Ulbrich <chat\-to\-me[at]raveit.de>.
.PP
This manual page was written Vangelis Mouhtsis <vangelis[AT]gnugr.org>,
for the Debian MATE Packaging Team, and may be used by others.
.SH LICENSING
Both the caja-actions source code and this man page are licensed under
the GNU General Public License (v2 or higher).
